# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gdb
            - apport
            - nvidia-opencl-dev

#cache:
#  directories:
#    - ${OPENCL_ROOT}

cache:
  directories:
    - ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}
    - ${POCL_ROOT}

before_install:
  - |
    if [[  ${TRAVIS_OS_NAME} == "linux" && ${OPENCL_LIB} == "pocl" ]]; then
      mkdir -p ${DEPS_DIR}
      if [ -z "$(ls -A ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION})" ]; then
        POCL_LLVM_URL=http://llvm.org/releases/${POCL_LLVM_VERSION}/clang+llvm-${POCL_LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz
        mkdir -p ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}
        travis_retry wget --no-check-certificate --quiet -O llvm-${POCL_LLVM_VERSION}.tar.xz ${POCL_LLVM_URL}
        tar xf llvm-${POCL_LLVM_VERSION}.tar.xz -C ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION} --strip-components 1
      else
        echo 'Using cached LLVM.'
      fi
    fi


  - |
    if [[  ${TRAVIS_OS_NAME} == "linux" && ${OPENCLU_LIB} == "amdappsdk" ]]; then
      mkdir -p ${OPENCL_ROOT}
      bash .travis/amd_sdk.sh ${AMDAPPSDK_VERSION}
      tar -xjf AMD-SDK.tar.bz2
      export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors
      mkdir -p ${OPENCL_VENDOR_PATH}
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT}
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd
      export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH}
      export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64;
      chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo
      ${AMDAPPSDKROOT}/bin/x86_64/clinfo
      rm AMD-APP-SDK*.sh
      rm AMD-SDK.tar.bz2
    fi
  # Download and install recent cmake
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL=${CMAKE_URL}
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

install:
  - export CPLUS_INCLUDE_PATH=${AMDAPPSDKROOT}/include
  - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH}
  - export LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LIBRARY_PATH}

before_script:
 - ulimit -c unlimited -S # Enable core dumps

# Build steps
script:
  - ./autogen.sh
  - ./configure  --without-opencl #--with-opencl=${AMDAPPSDKROOT}
  - make
  - make check

# after_failure:
#  - ls
#  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
#  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" ./benchmark -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

notifications:
  recipients:
    - msuchard@gmail.com
    - daniel@kotim.me
  email:
    on_success: change
    on_failure: always

env:
  global:
  - OPENCL_ROOT=$HOME/opencl
  - OPENCL_LIB=pocl
  - OPENCL_VERSION="12"
  - AMDAPPSDK_VERSION=291 # OpenCL 1.2
  - AMDAPPSDKROOT=${OPENCL_ROOT}/AMDAPPSDK
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - CMAKE_URL=https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz
  - OPENCL_HEADERS_VER="22"
  # POCL
  - POCL_BRANCH=release_1_0 # branch/tag
  - POCL_LLVM_VERSION=5.0.1
  - POCL_ROOT=${OPENCL_ROOT}/pocl-${POCL_BRANCH}/
  - POCL_LLVM_CONFIG=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/llvm-config
  - POCL_CXX_COMPILER=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/clang++
  - POCL_C_COMPILER=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/clang
  - POCL_OPENCL_LIB=${POCL_ROOT}/lib/libOpenCL.so
